### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SimoneSciacca75**
Hello there!

### CODE REVIEW

**Comment by SimoneSciacca75** [comment]
I'm gay

**Comment by GodOfDarkness88** [comment]
why are you gay

**Comment by SimoneSciacca75** [comment]
> why are you gay

idk

**Comment by GodOfDarkness88** [comment]
> > why are you gay
> 
> idk

are you stupid

**Comment by SimoneSciacca75** [comment]
SURPRISE MOTHER FUCKER!

**Pull request merged**
